### ISSUE TITLE
replace not working

### ISSUE THREAD

**Issue by feifeipan** [solidusjs/grunt-filerev-replace#10]
Code Structure:
app
 -tpl
  --index.html
 -js
  --page.js
  --libs.js
dest
 -tpl
  --index.html
 -js
  --page.js(concat with libs.js)

I run grunt-usemin to filerev js files, and I want to replace the js src with filerev-src in index.html

         filerev: {
            options: {
                algorithm: 'md5',
                length: 8
            },
            js: {
                src: 'app/js/**/*.js',
                dest: 'build/js'
            }
        },
        filerev_replace: {
            options: {
                assets_root: 'build/js'
            },
            // compiled_assets: {
            //     src:  ['build/js/*.js']
            // },
            views: {
                src: ['build/tpl/index.html']
            }
        }

Is anything wrong with my config?

**Comment by kvedananda** [comment]
Doesn't work for me either. Were you able to find a solution?

**Comment by joanniclaborde** [comment]
I think you're missing the `views_root` option, since it defaults to `assets_root` when missing. In your case, it doesn't make sense, since your templates are not located within `assets_root`.

Assuming your web server serves the assets from `build/js` (as you specified in `assets_root`) and the templates from `build/tpl`, I'm guessing something like this would work better:
```javascript
    filerev_replace: {
        options: {
            assets_root: 'build/js',
            views_root: 'build/tpl'
        },
        views: {
            src: ['build/tpl/index.html']
        }
    }
```

This means your html would look like this `<script src="/page.js"></script>` or this `<script src="page.js"></script>`.

I'm closing this issue for now, it's probably just a misconfiguration.
